Update Android Photo App Guidelines
minio/android-photo-app pull request #13
Opened 2017-07-12 23:44 UTC by CarterMcClellan

Change verbiage to adapt to Android Studio updates. Update content_main.xml and mainactivity.java.

2017-07-13 18:28 UTC, deekoder requested changes

2017-07-13 18:28 UTC, deekoder commented on README.md
> +![minio_ANDROID2](docs/screenshots/minio-ANDROID2.jpg?raw=true)
I think we need full paths in these URLs. Because it will work in github but not when streamed from docs.minio.io.

2017-07-13 18:28 UTC, deekoder commented on README.md
> +![minio_ANDROID3](docs/screenshots/minio-Android-os.png?raw=true)
Same as above. Open the image in github. Right click and copy image address to get full path.

2017-07-13 18:28 UTC, deekoder commented on README.md
>              System.out.println("In Post Execute");
Please remove.

2017-07-13 18:28 UTC, deekoder commented on app/src/main/java/example/minio/com/myphotosapp/MainActivity.java
> +    private static final String PHOTOSERVICE_URL = "http://192.168.220.125:8080/PhotoAPIService/minio/photoservice/list";
Needs to be a play URL

2017-07-15 00:30 UTC, harshavardhana requested changes

2017-07-15 00:30 UTC, harshavardhana commented on app/src/main/java/example/minio/com/myphotosapp/MainActivity.java
> +                System.out.println(httpCon);
We don't need this..

2017-07-15 00:30 UTC, harshavardhana commented on app/src/main/java/example/minio/com/myphotosapp/MainActivity.java
> +                System.out.println(imageJSON.getJSONObject(rindex).getString("url"));
Don't need this either..

2017-07-18 01:36 UTC, closed without merging