Change design palette to layouts. Change layout width and height to m…
minio/android-photo-app pull request #14
Opened 2017-07-18 01:36 UTC by CarterMcClellan

Change design palette to layouts. Change layout width and height to match parent (seen in xml).Update to indicate that the layout must be constrained on content-main.xml. Update image and text to latest version of android (Nougat). Paste updated xml (done), andMainActivity (done)

2017-07-18 04:00 UTC, deekoder requested changes

2017-07-18 04:00 UTC, deekoder commented on app/src/main/java/examples/minio/com/androidphotoapp/MainActivity.java
> +package examples.minio.com.androidphotoapp;
Needs License.

2017-07-23 08:06 UTC, harshavardhana commented
Commit title can be more concise..

2017-07-25 22:00 UTC, deekoder approved these changes

2017-07-25 22:15 UTC, deekoder approved these changes

2017-07-25 22:59 UTC, harshavardhana approved these changes
LGTM..

2017-07-26 18:48 UTC, merged